controller_manager:
  ros__parameters:
    update_rate: 200
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    position_controller:
      type: position_controllers/JointGroupPositionController
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    state_publish_rate: 100

  # Publish all joint states -----------------------------------
joint_trajectory_controller:
  ros__parameters:
    joints: 
      - j_pan
      - j_pelvis_l
      - j_pelvis_r
      - j_shoulder_l
      - j_shoulder_r
      - j_tilt
      - j_thigh1_l
      - j_thigh1_r
      - j_high_arm_l
      - j_high_arm_r
      - j_thigh2_l
      - j_thigh2_r
      - j_low_arm_l
      - j_low_arm_r
      - j_tibia_l
      - j_tibia_r
      - j_gripper_l
      - j_gripper_r
      - j_ankle1_l
      - j_ankle1_r
      - j_ankle2_l
      - j_ankle2_r
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    interpolate_from_desired_state: true
    
  

  # Position Controllers ---------------------------------------
position_controller:
  ros__parameters:
    joints: 
      - j_pan
      - j_pelvis_l
      - j_pelvis_r
      - j_shoulder_l
      - j_shoulder_r
      - j_tilt
      - j_thigh1_l
      - j_thigh1_r
      - j_high_arm_l
      - j_high_arm_r
      - j_thigh2_l
      - j_thigh2_r
      - j_low_arm_l
      - j_low_arm_r
      - j_tibia_l
      - j_tibia_r
      - j_gripper_l
      - j_gripper_r
      - j_ankle1_l
      - j_ankle1_r
      - j_ankle2_l
      - j_ankle2_r
